fix: try to improve transition on safari
cubik-so/cubik pull request #446
Opened 2023-12-25 12:57 UTC by Dank-del

2023-12-25 13:26 UTC, irffanasiff commented
@Dank-del it actually removed the transition from mac/web browser and now there is a different transition on mobile i dont think this is the solution to it - https://square-docs-git-transition-fix-cubik-team.vercel.app/components/disclosure/tabs

2023-12-25 16:35 UTC, irffanasiff requested changes

2023-12-25 16:35 UTC, irffanasiff commented on packages/ui/components/ui/Tabs/tabs.tsx
@dhruvsol @Dank-del

2023-12-25 17:10 UTC, Dank-del commented
unable to find the root cause of the issue but i will list my findings
- Using -webkit-transform: translate3d(0,0,0); to give a hardware acceleration did not work on safari
- rewrote the hook and memoized function sped up the ui a bit but did not completely fix the stuttery ui on safari
- [setting transition property to color also does not have any effect](https://joelglovier.com/writing/solution-for-css-transitions-crashing-safari)

2023-12-28 13:26 UTC, dhruvsol commented
we solved it closing it

2023-12-28 13:26 UTC, closed without merging