Fetch data project admin
cubik-so/cubik pull request #465
Opened 2023-12-29 10:41 UTC by Dank-del

2023-12-29 10:48 UTC, Dank-del commented
<img width="880" alt="Screenshot 2023-12-29 at 4 16 34 PM" src="https://github.com/cubik-so/cubik/assets/63096193/542d9f2f-51bf-4641-bad2-3bcb699dc35d">
Interesting how it does build on local machine.. does it fail due to some env var here?

2024-01-03 04:15 UTC, dhruvsol requested changes

2024-01-03 04:15 UTC, dhruvsol commented on apps/web/src/app/project/[slug]/components/projectDetailsPageHeader.tsx
> +  React.useEffect(() => {
why are you seting this here ?

2024-01-03 04:15 UTC, dhruvsol commented on apps/web/src/app/project/[slug]/components/projectDetailsPageHeader.tsx
> +  React.useEffect(() => {
also dont set any state directly in useEffect cause a lot of re-render even with specific things pass in the array

2024-01-03 04:15 UTC, dhruvsol commented on apps/web/src/app/project/[slug]/components/tabs/projectContributorsTab.tsx
> +                <div
use <Spinner/>

2024-01-03 04:15 UTC, dhruvsol commented on apps/web/src/app/project/[slug]/components/tabs/projectDetailsTab.tsx
>                // @ts-ignore
whats the type issue your getting ?

2024-01-03 04:15 UTC, dhruvsol commented on apps/web/src/app/project/[slug]/actions.ts
> +    if (!comment) {
throw a error in this case so we can handle it on client side pop a user by toast or something

2024-01-03 07:41 UTC, Dank-del commented on apps/web/src/app/project/[slug]/components/projectDetailsPageHeader.tsx
> +  React.useEffect(() => {
this is for default event state

2024-01-03 08:34 UTC, Dank-del commented on apps/web/src/app/project/[slug]/components/tabs/projectDetailsTab.tsx
>                // @ts-ignore
<img width="768" alt="Screenshot 2024-01-03 at 2 03 47 PM" src="https://github.com/cubik-so/cubik/assets/63096193/5ea4f25b-6094-4d70-8d16-bcfe537126bb">
<img width="758" alt="Screenshot 2024-01-03 at 2 04 05 PM" src="https://github.com/cubik-so/cubik/assets/63096193/39cf70be-cd91-49dc-b162-6b3714f152b4">

2024-01-03 08:36 UTC, Dank-del commented on apps/web/src/app/project/[slug]/components/tabs/projectDetailsTab.tsx
>                // @ts-ignore
<img width="859" alt="Screenshot 2024-01-03 at 2 06 12 PM" src="https://github.com/cubik-so/cubik/assets/63096193/2ee5b352-c5c5-4dae-87b9-56462f2f833a">
But I do have slides in it, its just a slightly modified fetch action which already was there before i worked on it.

2024-01-04 09:01 UTC, dhruvsol requested changes

2024-01-04 09:01 UTC, dhruvsol commented on packages/ui/components/ui/MenuList/MenuList.tsx
> +          <Text className="b1 md:l2-light-light" color={'inherit'}>
there is no l2-light-light

2024-01-04 09:01 UTC, dhruvsol commented on packages/ui/components/ui/MenuList/MenuList.tsx
> +          <Text className="b1 md:l2-light-light" color={'inherit'}>
change to l2-light

2024-01-04 10:57 UTC, merged